# Generated by Django 6.0 on 2025-12-30 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherObservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=255)),
                ('temperature', models.FloatField()),
                ('humidity', models.FloatField()),
                ('pressure', models.FloatField(blank=True, null=True)),
                ('description', models.CharField(default='Clear sky', max_length=255)),
                ('wind_speed', models.FloatField(blank=True, null=True)),
                ('wind_direction', models.IntegerField(blank=True, null=True)),
                ('observation_time', models.DateTimeField(auto_now_add=True)),
                ('source', models.CharField(default='manual', max_length=50)),
            ],
            options={
                'ordering': ['-observation_time'],
            },
        ),
    ]
